{"href": "http://www.scmp.com/news/hong-kong/economy/article/2113521/new-internet-looks-keep-user-data-away-tech-giants-and-bypass", "comments": "https://www.reddit.com/r/technology/comments/73rktn/new_internet_looks_to_keep_user_data_away_from/", "title": "\u2018New internet\u2019 looks to keep user data away from tech giants and bypass China censorship"}
{"href": "http://www.reuters.com/article/us-usa-cyber-russia-hpe-specialreport/special-report-hp-enterprise-let-russia-scrutinize-cyberdefense-system-used-by-pentagon-idUSKCN1C716M", "comments": "https://www.reddit.com/r/technology/comments/73sarg/special_report_hp_enterprise_let_russia/", "title": "Special Report: HP Enterprise let Russia scrutinize cyberdefense system used by Pentagon | Reuters"}
{"href": "/r/technology/comments/73oasy/if_network_neutrality_is_rolled_back_we_are/", "comments": "https://www.reddit.com/r/technology/comments/73oasy/if_network_neutrality_is_rolled_back_we_are/", "title": "If Network Neutrality is rolled back, we are essentially going to be paying for data at some point. It should therefore be our choice where our data goes, and we should then have the right to block or forgo advertising. Right?"}
{"href": "https://www.electronicsweekly.com/news/business/market-research/brits-dont-want-smart-homes-snoop-2017-09/", "comments": "https://www.reddit.com/r/technology/comments/73rtos/76_of_britons_are_fearful_of_the_smart_homes/", "title": "76% of Britons are \u2018fearful\u2019 of the smart homes concept"}
{"href": "https://arstechnica.com/?post_type=post&p=1177889", "comments": "https://www.reddit.com/r/technology/comments/73ssko/gambler_hits_14m_jackpot_casino_says_bingo/", "title": "Gambler hits $1.4M jackpot, casino says bingo machine \u201cmalfunctioned\u201d"}
{"href": "/r/MachineLearning/comments/73n9pm/d_confession_as_an_ai_researcher_seeking_advice/", "comments": "https://www.reddit.com/r/MachineLearning/comments/73n9pm/d_confession_as_an_ai_researcher_seeking_advice/", "title": "[D] Confession as an AI researcher; seeking advice"}
{"href": "https://www.technologyreview.com/s/608911/is-ai-riding-a-one-trick-pony/", "comments": "https://www.reddit.com/r/MachineLearning/comments/73qky1/r_hinton_most_conferences_consist_of_making_minor/", "title": "[R] Hinton: \u201cMost conferences consist of making minor variations \u2026 as opposed to thinking hard and saying, \u2018What is it about what we\u2019re doing now that\u2019s really deficient? What does it have difficulty with? Let\u2019s focus on that.\u2019\u201d"}
{"href": "/r/MachineLearning/comments/73rtd7/d_do_you_still_use_relu_if_so_why/", "comments": "https://www.reddit.com/r/MachineLearning/comments/73rtd7/d_do_you_still_use_relu_if_so_why/", "title": "[D] Do you still use ReLU? If so, why?"}
{"href": "https://www.youtube.com/watch?v=DYhAM34Hhzc", "comments": "https://www.reddit.com/r/MachineLearning/comments/73ru14/p_the_end_of_privacy_by_michal_kosinski_keynote/", "title": "[P] \"The End of Privacy\" by Michal Kosinski, Keynote at CeBIT'17 (personality from FB likes and photos)"}
{"href": "/r/MachineLearning/comments/73sa8k/d_reparameterization_mean_sigmastandard_normal/", "comments": "https://www.reddit.com/r/MachineLearning/comments/73sa8k/d_reparameterization_mean_sigmastandard_normal/", "title": "[D] Reparameterization: mean + sigma*standard normal noise, the noise is N(0, 1) or N(0, I), i.e. each noise for all dimensions or individual dimension ?"}
{"href": "/r/dataisbeautiful/comments/73r23u/traffic_accidents_in_the_uk_animated_from_2009_to/", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73r23u/traffic_accidents_in_the_uk_animated_from_2009_to/", "title": "Traffic accidents in the UK, animated from 2009 to 2014 [OC]"}
{"href": "/r/dataisbeautiful/comments/73nkb5/oc_how_frequently_my_crush_makes_contact_with_me/", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73nkb5/oc_how_frequently_my_crush_makes_contact_with_me/", "title": "[OC] How frequently my crush makes contact with me"}
{"href": "http://www.businessinsider.com/tom-cruise-much-older-than-love-interests-2017-9", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73p07a/as_tom_cruise_gets_older_his_onscreen_love/", "title": "As Tom Cruise gets older, his on-screen love interests stay the same age"}
{"href": "/r/dataisbeautiful/comments/73n9e9/animation_of_all_trains_from_beijing_oc/", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73n9e9/animation_of_all_trains_from_beijing_oc/", "title": "Animation of all trains from Beijing [OC]"}
{"href": "https://i.imgur.com/ZGkokh9.jpg", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73nc58/the_eu4_game_world_map_as_a_network_graph_x_post/", "title": "The EU4 (game) World Map as a network graph (X post /eu4) [OC]"}
{"href": "https://youtu.be/i9bkKw32dGw", "comments": "https://www.reddit.com/r/programming/comments/73nnv1/clever_way_of_skirting_game_code_quality_tests/", "title": "Clever way of skirting game code quality tests from the 90s (x-post /r/Games)"}
{"href": "https://en.wikipedia.org/wiki/S3_Texture_Compression", "comments": "https://www.reddit.com/r/programming/comments/73qka2/the_patent_on_s3_texture_compression_has_expired/", "title": "The patent on S3 texture compression has expired"}
{"href": "https://dolphin-emu.org/blog/2017/10/02/dolphin-progress-report-september-2017/", "comments": "https://www.reddit.com/r/programming/comments/73r3ia/dolphin_progress_report_september_2017/", "title": "Dolphin Progress Report: September 2017"}
{"href": "https://savecodeshare.eu/", "comments": "https://www.reddit.com/r/programming/comments/73qp6f/the_eu_copyright_reform_threatens_free_and_open/", "title": "The EU #copyright reform threatens Free and Open Source Software. Sign the open letter and #savecodeshare!"}
{"href": "https://www.youtube.com/watch?v=5SBEAZIfDAg", "comments": "https://www.reddit.com/r/programming/comments/73pcmx/snes_background_modes_06_super_nintendo/", "title": "SNES Background Modes 0-6 - Super Nintendo Entertainment System Features Pt. 04"}
{"href": "/r/Python/comments/73mh0k/python_script_to_measure_3d_object_volume/", "comments": "https://www.reddit.com/r/Python/comments/73mh0k/python_script_to_measure_3d_object_volume/", "title": "python script to measure 3D object volume"}
{"href": "https://github.com/ManrajGrover/halo", "comments": "https://www.reddit.com/r/Python/comments/73r9co/halo_beautiful_terminal_spinners_for_your_python/", "title": "Halo - Beautiful Terminal Spinners for Your Python Command Line Applications"}
{"href": "http://www.deepideas.net/deep-learning-from-scratch-i-computational-graphs/", "comments": "https://www.reddit.com/r/Python/comments/73q3qb/deep_learning_from_scratch_i_computational_graphs/", "title": "Deep Learning From Scratch I: Computational Graphs"}
{"href": "https://pypi.python.org/pypi/notifiers", "comments": "https://www.reddit.com/r/Python/comments/73rb5r/notifiers_v051_easily_send_notifications_now/", "title": "Notifiers v0.5.1 - Easily send notifications, now supporting 6 providers"}
{"href": "https://simpleisbetterthancomplex.com/series/2017/10/02/a-complete-beginners-guide-to-django-part-5.html", "comments": "https://www.reddit.com/r/Python/comments/73sr7x/a_complete_beginners_guide_to_django/", "title": "A Complete Beginner's Guide to Django"}
{"href": "http://www.scmp.com/news/hong-kong/economy/article/2113521/new-internet-looks-keep-user-data-away-tech-giants-and-bypass", "comments": "https://www.reddit.com/r/technology/comments/73rktn/new_internet_looks_to_keep_user_data_away_from/", "title": "\u2018New internet\u2019 looks to keep user data away from tech giants and bypass China censorship"}
{"href": "http://www.reuters.com/article/us-usa-cyber-russia-hpe-specialreport/special-report-hp-enterprise-let-russia-scrutinize-cyberdefense-system-used-by-pentagon-idUSKCN1C716M", "comments": "https://www.reddit.com/r/technology/comments/73sarg/special_report_hp_enterprise_let_russia/", "title": "Special Report: HP Enterprise let Russia scrutinize cyberdefense system used by Pentagon | Reuters"}
{"href": "/r/technology/comments/73oasy/if_network_neutrality_is_rolled_back_we_are/", "comments": "https://www.reddit.com/r/technology/comments/73oasy/if_network_neutrality_is_rolled_back_we_are/", "title": "If Network Neutrality is rolled back, we are essentially going to be paying for data at some point. It should therefore be our choice where our data goes, and we should then have the right to block or forgo advertising. Right?"}
{"href": "https://www.electronicsweekly.com/news/business/market-research/brits-dont-want-smart-homes-snoop-2017-09/", "comments": "https://www.reddit.com/r/technology/comments/73rtos/76_of_britons_are_fearful_of_the_smart_homes/", "title": "76% of Britons are \u2018fearful\u2019 of the smart homes concept"}
{"href": "https://arstechnica.com/?post_type=post&p=1177889", "comments": "https://www.reddit.com/r/technology/comments/73ssko/gambler_hits_14m_jackpot_casino_says_bingo/", "title": "Gambler hits $1.4M jackpot, casino says bingo machine \u201cmalfunctioned\u201d"}
{"href": "/r/MachineLearning/comments/73n9pm/d_confession_as_an_ai_researcher_seeking_advice/", "comments": "https://www.reddit.com/r/MachineLearning/comments/73n9pm/d_confession_as_an_ai_researcher_seeking_advice/", "title": "[D] Confession as an AI researcher; seeking advice"}
{"href": "https://www.technologyreview.com/s/608911/is-ai-riding-a-one-trick-pony/", "comments": "https://www.reddit.com/r/MachineLearning/comments/73qky1/r_hinton_most_conferences_consist_of_making_minor/", "title": "[R] Hinton: \u201cMost conferences consist of making minor variations \u2026 as opposed to thinking hard and saying, \u2018What is it about what we\u2019re doing now that\u2019s really deficient? What does it have difficulty with? Let\u2019s focus on that.\u2019\u201d"}
{"href": "/r/MachineLearning/comments/73rtd7/d_do_you_still_use_relu_if_so_why/", "comments": "https://www.reddit.com/r/MachineLearning/comments/73rtd7/d_do_you_still_use_relu_if_so_why/", "title": "[D] Do you still use ReLU? If so, why?"}
{"href": "https://www.youtube.com/watch?v=DYhAM34Hhzc", "comments": "https://www.reddit.com/r/MachineLearning/comments/73ru14/p_the_end_of_privacy_by_michal_kosinski_keynote/", "title": "[P] \"The End of Privacy\" by Michal Kosinski, Keynote at CeBIT'17 (personality from FB likes and photos)"}
{"href": "/r/MachineLearning/comments/73sa8k/d_reparameterization_mean_sigmastandard_normal/", "comments": "https://www.reddit.com/r/MachineLearning/comments/73sa8k/d_reparameterization_mean_sigmastandard_normal/", "title": "[D] Reparameterization: mean + sigma*standard normal noise, the noise is N(0, 1) or N(0, I), i.e. each noise for all dimensions or individual dimension ?"}
{"href": "/r/dataisbeautiful/comments/73r23u/traffic_accidents_in_the_uk_animated_from_2009_to/", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73r23u/traffic_accidents_in_the_uk_animated_from_2009_to/", "title": "Traffic accidents in the UK, animated from 2009 to 2014 [OC]"}
{"href": "/r/dataisbeautiful/comments/73nkb5/oc_how_frequently_my_crush_makes_contact_with_me/", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73nkb5/oc_how_frequently_my_crush_makes_contact_with_me/", "title": "[OC] How frequently my crush makes contact with me"}
{"href": "http://www.businessinsider.com/tom-cruise-much-older-than-love-interests-2017-9", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73p07a/as_tom_cruise_gets_older_his_onscreen_love/", "title": "As Tom Cruise gets older, his on-screen love interests stay the same age"}
{"href": "/r/dataisbeautiful/comments/73n9e9/animation_of_all_trains_from_beijing_oc/", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73n9e9/animation_of_all_trains_from_beijing_oc/", "title": "Animation of all trains from Beijing [OC]"}
{"href": "https://i.imgur.com/ZGkokh9.jpg", "comments": "https://www.reddit.com/r/dataisbeautiful/comments/73nc58/the_eu4_game_world_map_as_a_network_graph_x_post/", "title": "The EU4 (game) World Map as a network graph (X post /eu4) [OC]"}
{"href": "https://youtu.be/i9bkKw32dGw", "comments": "https://www.reddit.com/r/programming/comments/73nnv1/clever_way_of_skirting_game_code_quality_tests/", "title": "Clever way of skirting game code quality tests from the 90s (x-post /r/Games)"}
{"href": "https://en.wikipedia.org/wiki/S3_Texture_Compression", "comments": "https://www.reddit.com/r/programming/comments/73qka2/the_patent_on_s3_texture_compression_has_expired/", "title": "The patent on S3 texture compression has expired"}
{"href": "https://dolphin-emu.org/blog/2017/10/02/dolphin-progress-report-september-2017/", "comments": "https://www.reddit.com/r/programming/comments/73r3ia/dolphin_progress_report_september_2017/", "title": "Dolphin Progress Report: September 2017"}
{"href": "https://savecodeshare.eu/", "comments": "https://www.reddit.com/r/programming/comments/73qp6f/the_eu_copyright_reform_threatens_free_and_open/", "title": "The EU #copyright reform threatens Free and Open Source Software. Sign the open letter and #savecodeshare!"}
{"href": "https://www.youtube.com/watch?v=5SBEAZIfDAg", "comments": "https://www.reddit.com/r/programming/comments/73pcmx/snes_background_modes_06_super_nintendo/", "title": "SNES Background Modes 0-6 - Super Nintendo Entertainment System Features Pt. 04"}
{"href": "/r/Python/comments/73mh0k/python_script_to_measure_3d_object_volume/", "comments": "https://www.reddit.com/r/Python/comments/73mh0k/python_script_to_measure_3d_object_volume/", "title": "python script to measure 3D object volume"}
{"href": "https://github.com/ManrajGrover/halo", "comments": "https://www.reddit.com/r/Python/comments/73r9co/halo_beautiful_terminal_spinners_for_your_python/", "title": "Halo - Beautiful Terminal Spinners for Your Python Command Line Applications"}
{"href": "http://www.deepideas.net/deep-learning-from-scratch-i-computational-graphs/", "comments": "https://www.reddit.com/r/Python/comments/73q3qb/deep_learning_from_scratch_i_computational_graphs/", "title": "Deep Learning From Scratch I: Computational Graphs"}
{"href": "https://pypi.python.org/pypi/notifiers", "comments": "https://www.reddit.com/r/Python/comments/73rb5r/notifiers_v051_easily_send_notifications_now/", "title": "Notifiers v0.5.1 - Easily send notifications, now supporting 6 providers"}
{"href": "https://simpleisbetterthancomplex.com/series/2017/10/02/a-complete-beginners-guide-to-django-part-5.html", "comments": "https://www.reddit.com/r/Python/comments/73sr7x/a_complete_beginners_guide_to_django/", "title": "A Complete Beginner's Guide to Django"}
